spring:
  application:
    name: IlpTutorialRestService

info:
  app:
    name: IlpTutorialRestService
    description: This is the ILP Tutorial Rest Service
    version: 3.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true

